FROM camunda/camunda-bpm-platform:tomcat-latest

ADD target/Auslandssemesterportal.war /camunda/webapps/Auslandssemesterportal.war
ADD tomcat-users.xml /camunda/conf/tomcat-users.xml
Add manager.xml /camunda/conf/Catalina/localhost/manager.xml